In [8]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
from pprint import pprint

main_url = 'https://catalog.upenn.edu/courses/'
page_data = requests.get(main_url)

soup = BeautifulSoup(page_data.content, 'html.parser')

pages = soup.find(id='content')
depts = pages.find_all('a')

link_extensions = []
for dept in depts:
    link = dept.get('href')
    if isinstance(link, str) == True and '/courses/' in link:
        link_extensions.append(link)

base_url = 'https://catalog.upenn.edu'

courses_dict = {
    'department' : [],
    'course_name' : [],
    'course_description' : [],
    'instructor' : [],
    'course_type' : [],
    'credit_units' : [],
    'course_prereqs' : [],
    'term' : [],
    'also_offered_as' : []
}
counter = 0
for link in link_extensions:
    full_url = base_url + link
    dept_abbreviation = link.replace('/courses/','').replace('/','').strip()
    
    page_data = requests.get(full_url)

    soup = BeautifulSoup(page_data.content, 'html.parser')

    results = soup.find(id='content')

    courses = results.find_all('div', class_='courseblock')

    for course in courses:
        course_name = str(course.find('p', class_='courseblocktitle noindent').text.strip())
        course_elements = course.find_all('p', class_='courseblockextra noindent')
        course_description = 'Unknown'
        instructor = 'Unknown'
        course_type = 'Unknown'
        credit_units = 'Unknown'
        course_prereqs = 'No Pre-Requisites for this Course'
        term = 'Unknown'
        also_offered_as = 'No Other Courses Match This Course'
        for element in course_elements:
            if 'Taught by' in element.text:
                instructor = element.text.replace('Taught by:','').strip()
            elif 'Activity:' in element.text:
                course_type = element.text.replace('Activity:', '').strip()
            elif 'Course Unit' in element.text:
                credit_units = element.text.replace('Course Unit', '').strip()
            elif 'Prerequisite:' in element.text:
                if course_name == 'ANTH 058  Freshman Seminar':
                    prereq_text = element.text.split('Prerequisite:',1)[1].strip()
#                 course_prereqs = element.text.replace('Prerequisite:', '').strip()
            elif 'course' in element.text.lower() and 'term' in element.text.lower() and 'offered' in element.text.lower():
                term = element.text
            elif 'Also Offered As:' in element.text:
                also_offered_as = element.text.replace('Also Offered As:', '').strip()
            else:
                course_description = element.text
        courses_dict['department'].append(dept_abbreviation)
        courses_dict['course_name'].append(str(course_name))
        courses_dict['course_description'].append(course_description)
        courses_dict['instructor'].append(instructor)
        courses_dict['course_type'].append(course_type)
        courses_dict['credit_units'].append(credit_units)
        courses_dict['course_prereqs'].append(course_prereqs)
        courses_dict['term'].append(term)
        courses_dict['also_offered_as'].append(also_offered_as)
        counter += 1
        if counter % 100 == 0:
            print(counter)

courses_df = pd.DataFrame(courses_dict)
courses_df.to_csv('/Users/arvindbala/Desktop/grad_courses.csv', index=False)
courses_df

100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700

,department,course_name,course_description,instructor,course_type,credit_units,course_prereqs,term,also_offered_as
0,acfd,ACFD 600 Personal Development I,Unknown,"Jessica Dine, MD",Hybrid Course,0.5 s,No Pre-Requisites for this Course,Unknown,No Other Courses Match This Course
1,acfd,ACFD 601 Scholarship Development I,Unknown,"Jessica Dine, MD",Hybrid Course,0.5 s,No Pre-Requisites for this Course,Unknown,No Other Courses Match This Course
2,acfd,ACFD 602 Personal Development II,Unknown,"Jessica Dine, MD",Hybrid Course,0.5 s,No Pre-Requisites for this Course,Unknown,No Other Courses Match This Course
3,acfd,ACFD 603 Scholarship Development II,Unknown,"Jessica Dine, MD",Hybrid Course,0.5 s,No Pre-Requisites for this Course,Unknown,No Other Courses Match This Course
4,acct,ACCT 101 Accounting and Financial Reporting,This course is an introduction to the basic co...,Unknown,Lecture,1.0,No Pre-Requisites for this Course,One-term course offered either term,No Other Courses Match This Course
...,...,...,...,...,...,...,...,...,...
9746,zulu,ZULU 251 Intermediate Zulu II,For BA Students: Last Language Course,Unknown,Lecture,1.0,No Pre-Requisites for this Course,Course usually offered in spring term,No Other Courses Match This Course
9747,zulu,ZULU 350 Advanced Zulu I,For BA Students: Advanced Language Course,Mbeje,Lecture,1.0,No Pre-Requisites for this Course,Course usually offered in fall term,No Other Courses Match This Course
9748,zulu,ZULU 351 Advanced Zulu II,For BA Students: Advanced Language Course,Mbeje,Lecture,1.0,No Pre-Requisites for this Course,Course usually offered in spring term,No Other Courses Match This Course
9749,zulu,ZULU 450 Zulu Language and Culture I,Unknown,Unknown,Lecture,1.0,No Pre-Requisites for this Course,Course usually offered in spring term,No Other Courses Match This Course
9750,zulu,ZULU 451 Zulu Language and Culture II,For BA Students: Advanced Language Course,Unknown,Lecture,1.0,No Pre-Requisites for this Course,Course usually offered in spring term,No Other Courses Match This Course

In [9]:
def extract_course_num(course_name):
    course_num = [int(i) for i in course_name.split() if i.isdigit()][0]
    return course_num

courses_df['course_number'] = courses_df['course_name'].apply(extract_course_num)
courses_df = courses_df[['department','course_number','course_name','course_description','instructor','course_type','credit_units','course_prereqs','term','also_offered_as']]
courses_df.to_csv('/Users/arvindbala/Desktop/MBDS/TA Stuff/516/Lecture 11/course_scraper/courses.csv', index=False)